[[runners]]
  [runners.feature_flags]
    FF_USE_FASTZIP = true
  [runners.docker]
    tls_verify = false
    image = "busybox"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    pull_policy = ["if-not-present"]
    shm_size = 0
    volumes = [
      "/builds:/builds",
      "/var/run/docker.sock:/var/run/docker.sock:rw",
      "/etc/docker:/etc/docker:ro",
    ]
